<?php

/**
 * @file
 * Code for the Playbox Global Settings module.
 */

/*
 * Implements hook_init()
 */
function playbox_admin_init() {
  // Load CSS
  $playbox_admin_color = variable_get('playbox_admin_color');
  if(isset($playbox_admin_color) && $playbox_admin_color == 0) {
    drupal_add_css(drupal_get_path('module', 'playbox_admin') . '/css/crimson.css');
  }

}

/*
 * Implements hook_menu()
 */
function playbox_admin_menu() {
  $items['admin/config/playbox'] = array(
    'title' => 'Playbox',
    'position' => 'left',
    'weight' => 200,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer site configuration'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );

  $items['admin/config/playbox/global-settings'] = array(
    'title' => 'Global Settings',
    'description' => t('Configure global settings for Playbox'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('playbox_admin_form'),
    'access callback' => TRUE,
  );

  return $items;
}

/*
 * Implements hook_permission()
 */
function playbox_admin_permission() {
  return array(
    'administer my module' => array(
      'title' => t('Administer Playbox Global Settings'),
      'description' => t('Perform administration tasks for Playbox Global Settings'),
    ),
  );
}

/*
 * Implements hook_form_FORM_ID_alter()
 */
function playbox_admin_form_playbox_admin_form_alter(&$form, &$form_state, $form_id) {
  $form['playbox_admin_color']['#empty_option'] = t('Choose a color');
}

/*
 * Helper function to return our colorz
 */
function _playbox_admin_get_colors() {
  return array (
    'crimson',
    'tangerine',
    'ochre',
    'chartreuse',
    'cerulean',
    'lavender',
    'onyx',
    'eggshell',
  );
}

/*
 * Playbox admin form definition
 */
function playbox_admin_form($form, &$form_state) {
  $form['playbox_admin_president'] = array(
    '#type' => 'entityreference',
    '#title' => t('Who is your favorite president?'),
    '#era_entity_type' => 'node',
    '#era_bundles' => array('playbox_president'),
    '#era_cardinality' => 1,
    '#era_query_settings' => array(
      'limit' => 15,
      ),
    '#default_value' => variable_get('playbox_admin_president')
  );

  $form['playbox_admin_boss'] = array(
    '#type' => 'entityreference',
    '#title' => t('Who is your favorite boss?'),
    '#era_entity_type' => 'node',
    '#era_bundles' => array('playbox_robot'),
    '#era_cardinality' => 1,
    '#era_query_settings' => array(
      'limit' => 15,
    ),
    '#default_value' => variable_get('playbox_admin_boss'),
  );

  $form['playbox_admin_color'] = array(
    '#type' => 'select',
    '#title' => t('What is your favorite color?'),
    '#options' => _playbox_admin_get_colors(),
    '#empty_option' => 'Select a color',
    '#default_value' => variable_get('playbox_admin_color'),
  );

  $form['playbox_admin_disco'] = array(
    '#type' => 'checkbox',
    '#title' => t('Put site into Disco Mode?'),
    '#default_value' => variable_get('playbox_admin_disco'),
  );

  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );
  return system_settings_form($form);
}
