<?php
/**
 * @file
 * Code for the Playbox Global Settings module.
 */

function playbox_admin_menu()	 {
	$items['admin/config/playbox'] = array(
    'title' => 'Playbox',
    'position' => 'left',
    'weight' => 200,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer site configuration'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  	);

	$items ['admin/config/playbox/global-settings'] = array(
		'title' => 'Global Settings',
		'description' => t('Configure global settings for Playbox'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('playbox_admin_form'),
		'access callback' => TRUE,
	);

	return $items;
}

function _playbox_admin() {
	return array (
		'#cc0000' => 'crimson', 
		'#ee8000' => 'tangerine', 
		'#ffb90f' => 'ochre',
		'#b8ff5c' => 'chartreuse', 
		'#38a5db' => 'cerulean', 
		'#d0aaf3' => 'lavender', 
		'#000000' => 'onyx', 
		'#ffffff' => 'eggshell',
		);
}

function playbox_admin_form($form, &$form_state) {
	$form['playbox_admin_president'] = array(
		'#type' => 'textfield',
		'#title' => t('Who is your favorite president?'),
		'#default_value' => variable_get('playbox_admin_president'),
	);

	$form['playbox_admin_boss'] = array(
		'#type' => 'textfield',
		'#title' => t('Who is your favorite boss?'),
		'#default_value' => variable_get('playbox_admin_boss'),
	);

	$form['playbox_admin_color'] = array(
		'#type' => 'select',
		'#title' => t('What is your favorite color?'),
		'#options' => _playbox_admin(),
		'#empty_option' => 'Select a color',
		'#default_value' => variable_get('playbox_admin_color'),
	);

	$form['playbox_admin_disco'] = array(
		'#type' => 'checkbox',
		'#title' => t('Put site into Disco Mode?'),
		'#default_value' => variable_get('playbox_admin_disco'),
	);

	$form['playbox_admin_description'] = array(
		'#value' => t('Playbox! is a sandbox-proving-ground for people interested in working with us here at Kalamuna. Its a magnificent and collaborative code-garden where would-be code artists, site builder and designers alike can play around and show what theyve got.'),
	);

	$form['actions']['submit'] = array(
		'#type' => 'submit',
		'#value' => t('Submit'),
	);
	return system_settings_form($form);
}

function playbox_admin_permission() {
	return array(
    'administer my module' => array(
      'title' => t('Administer Playbox Global Settings'),
      'description' => t('Perform administration tasks for Playbox Global Settings'),
    ),
  );
}

function playbox_admin_form_alter(&$form, &$form_state, $form_id) {
	$form['playbox_admin_color']['#empty_option'] = t('Choose a color');
}

function playbox_admin_init() {
  // Load CS and JS
  drupal_add_css(drupal_get_path('module', 'playbox_admin') . '/css/colors.css');
}

