<?php
/**
 * @file
 * Contains code for determining emergency threat level and altering views that
 * display presidents.
 */

/**
 * Implements hook_form_FORM_ID_alter().
 */
function playbox_ntas_form_playbox_admin_form_alter(&$form, &$form_state, $form_id) {
  // Add checkbox to global settings for testing this module.
  $form['playbox_global_settings']['playbox_admin_ntas'] = array(
    '#type' => 'checkbox',
    '#title' => t('Test continuity of government?'),
    '#default_value' => variable_get('playbox_admin_ntas'),
  );
}

/**
 * NTAS Supported Alert levels: http://www.dhs.gov/ntas-api-documentation
 * @see "The new NTAS system supports only two states"
 */
function playbox_ntas_threat_level_is_elevated() {
  $threat_cid = 'playbox_ntas_threat_level';
  $cache = cache_get($threat_cid);
  // If testing, override cache.
  if (empty($cache->data->level) || variable_get('playbox_admin_ntas')) {
    // If testing, use sample feed.
    $uri = variable_get('playbox_admin_ntas') ? 'http://www.dhs.gov/ntas/1.0/sample-feed.xml' : 'http://www.dhs.gov/ntas/1.0/alerts.xml';
    $response = drupal_http_request($uri);
    if (empty($response->error)) {
      $xml = new SimpleXMLElement($response->data);
      $alert = $xml->xpath('//alert');
      // As per NTAS documentation alert is either "high/critical" or none.
      // Thus we don't care what the actual alert is, as long as there's any at all.
      $status = (object) array(
        'level' => 'none',
      );

      if (count($alert)) {
        $status->level = 'high';
      }

      // Lets be nice and avoid hitting NTAS api frequently.
      $ntas_cache_lifespan = (int) variable_get('ntas_cache_lifespan', 60 * 60);
      cache_set($threat_cid, $status, "cache", $ntas_cache_lifespan);
      $cache = cache_get($threat_cid);
    }
  }

  return !empty($cache->data->level) && $cache->data->level == 'high';
}

function playbox_ntas_views_post_execute(&$view) {
  if ('playbox_battles' == $view->name && 'playbox_battles_featured_1' == $view->current_display) {
    $threat_level_is_elevated = playbox_ntas_threat_level_is_elevated();
    if ($threat_level_is_elevated) {
      // Find values to copy from VP to president when threat is high.
      // i.e. "swap pres for VP"
      $copy_map = array();
      foreach ($view->field as $key => $field) {
        if (in_array($field->relationship, array('node_field_data_field_playbox_president'))) {
          $copy_map['president'][$field->field_info['field_name']] = $field->options['id'];
        }
        elseif (in_array($field->relationship, array('node_field_data_field_running_mate'))) {
          $copy_map['vp'][$field->field_info['field_name']] = $field->options['id'];
        }
      }

      // Swap VP for pres.
      if (!empty($copy_map['vp'])) {
        foreach ($copy_map['vp'] as $key => $field_alias) {
          // Only attempt override when both president and VP have the same field.
          if (!empty($copy_map['president'][$key])) {
            $pres_key = 'field_' . $copy_map['president'][$key];
            $vp_key = 'field_' . $field_alias;
            foreach (array_keys($view->result) as $index) {
              if (!empty($view->result[$index]->{$vp_key})) {
                $view->result[$index]->{$pres_key} = $view->result[$index]->{$vp_key};
              }
            }
          }
        }
      }
    }
  }
}
