<?php
/**
 * @file
 * Code for the Playbox Global Settings module.
 */

function playbox_global_settings_menu()	 {
	$items['admin/config/playbox'] = array(
    'title' => 'Playbox',
    'position' => 'left',
    'weight' => 200,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer site configuration'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  	);

	$items ['admin/config/playbox/global-settings'] = array(
		'title' => 'Global Settings',
		'description' => t('Configure global settings for Playbox'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('playbox_global_settings_form'),
		'access callback' => TRUE,
	);

	return $items;
}

function _playbox_global_settings() {
	return array (
		'magenta', 
		'tangerine', 
		'ochre',
		'chartreuse', 
		'cerulean', 
		'lavender', 
		'onyx', 
		'eggshell',
		);
}

function playbox_global_settings_form($form, &$form_state) {
	$form['playbox_global_settings_president'] = array(
		'#type' => 'textfield',
		'#title' => t('Who is your favorite president?'),
		'#default_value' => variable_get('playbox_global_settings_president'),
	);

	$form['playbox_global_settings_boss'] = array(
		'#type' => 'textfield',
		'#title' => t('Who is your favorite boss?'),
		'#default_value' => variable_get('playbox_global_settings_boss'),
	);

	$form['playbox_global_settings_color'] = array(
		'#type' => 'select',
		'#title' => t('What is your favorite color?'),
		'#options' => _playbox_global_settings(),
		'#empty_option' => 'Select a color',
		'#default_value' => variable_get('playbox_global_settings_color'),
	);

	$form['playbox_global_settings_disco'] = array(
		'#type' => 'checkbox',
		'#title' => t('Put site into Disco Mode?'),
		'#default_value' => variable_get('playbox_global_settings_disco'),
	);

	$form['playbox_global_settings_description'] = array(
		'#value' => t('Playbox! is a sandbox-proving-ground for people interested in working with us here at Kalamuna. Its a magnificent and collaborative code-garden where would-be code artists, site builder and designers alike can play around and show what theyve got.'),
	);

	$form['actions']['submit'] = array(
		'#type' => 'submit',
		'#value' => t('Submit'),
	);
	return system_settings_form($form);
}

function playbox_global_settings_permission() {
	return array(
    'administer my module' => array(
      'title' => t('Administer Playbox Global Settings'),
      'description' => t('Perform administration tasks for Playbox Global Settings'),
    ),
  );
}

function playbox_global_settings_form_alter(&$form, &$form_state, $form_id) {
	$form['playbox_global_settings_color']['#empty_option'] = t('Choose a color');
}