<?php

/**
 * Implementation of hook_menu().
 */
function playbox_battle_dashboard_menu() {
  $items['playbox-battles/dashboard'] = array(
    'page callback' => 'playbox_battle_dashboard',
    'access arguments' => array('playbox battle dashboard'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function playbox_battle_dashboard_permission() {
  return array(
    'playbox battle dashboard' => array(
      'title' => t('View the battle dashboard'),
      'description' => t(''),
    ),
  );
}

function playbox_battle_dashboard(){
  $dashboard = '';
  $base_path = base_path();
  
  //Create new battles
  if(user_access('create playbox_battle content')){
    $dashboard .= '<h2><a href="'.$base_path.'node/add/playbox-battle">Create new battles</a></h2>';
  }
 
  //Change site-wide configuration
  if(user_access('change user playbox settings')){
    $dashboard .= '<h2><a href="'.$base_path.'admin/config/playbox/user-settings">Change site configuration</a></h2>';
  }
  
  //See my battles
  $my_battles = views_get_view('playbox_battles');
  $my_battles->set_display('my_battles');
  $dashboard .= '<h2>'.$my_battles->get_title().'</h2>';
  $dashboard .= $my_battles->preview();
  
  //See chosen team
  //TODO if user has permission
  
  
  return $dashboard;
}

//TODO add team affiliation to registration form


