<?php
// Plugin definition
$plugin = array(
  'title' => t('Playbox Rows'),
  'icon' => 'playbox-rows.png',
  'category' => t('Playbox'),
  'theme' => 'playbox_rows',
  'regions' => array(
    'jumbotron' => t('Jumbotron'),
    'row1' => t('Row 1'),
    'row2' => t('Row 2'),
    'row3' => t('Row 3'),
    'row4' => t('Row 4'),
    'row5' => t('Row 5'),
    'row6' => t('Row 6'),
    'row7' => t('Row 7'),
    'footer' => t('Footer'),
  ),
);
