<?php
/**
 * @file
 * playbox_robots.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function playbox_robots_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'node-playbox_robot-field_playbox_bio'
  $field_instances['node-playbox_robot-field_playbox_bio'] = array(
    'bundle' => 'playbox_robot',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'A brief bio about your would-be robot overlord detailing things like how many humans he\'s vaporized or where he summered as a childbot.',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 1,
      ),
      'featured' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_playbox_bio',
    'label' => 'Bio',
    'required' => 1,
    'settings' => array(
      'linkit' => array(
        'button_text' => 'Search',
        'enable' => 0,
        'profile' => '',
      ),
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
      ),
      'type' => 'text_textarea',
      'weight' => 4,
    ),
  );

  // Exported field_instance: 'node-playbox_robot-field_playbox_nickname'
  $field_instances['node-playbox_robot-field_playbox_nickname'] = array(
    'bundle' => 'playbox_robot',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '"Blue Bomber", "Phil Collins", "Zero", etc',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 2,
      ),
      'featured' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_playbox_nickname',
    'label' => 'Nickname',
    'required' => 1,
    'settings' => array(
      'linkit' => array(
        'button_text' => 'Search',
        'enable' => 0,
        'profile' => '',
      ),
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 3,
    ),
  );

  // Exported field_instance: 'node-playbox_robot-field_playbox_portrait'
  $field_instances['node-playbox_robot-field_playbox_portrait'] = array(
    'bundle' => 'playbox_robot',
    'deleted' => 0,
    'description' => 'This is a nice portrait of the challenging robot overlord.',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'image',
        'settings' => array(
          'image_link' => '',
          'image_style' => '',
        ),
        'type' => 'image',
        'weight' => 0,
      ),
      'featured' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_playbox_portrait',
    'label' => 'Portrait',
    'required' => 1,
    'settings' => array(
      'alt_field' => 0,
      'default_image' => 0,
      'file_directory' => '',
      'file_extensions' => 'png gif jpg jpeg',
      'max_filesize' => '',
      'max_resolution' => '',
      'min_resolution' => '400x400',
      'title_field' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'media',
      'settings' => array(
        'allowed_schemes' => array(
          'private' => 'private',
          'public' => 'public',
          'vimeo' => 0,
          'youtube' => 0,
        ),
        'allowed_types' => array(
          'audio' => 0,
          'document' => 0,
          'image' => 'image',
          'video' => 0,
        ),
        'browser_plugins' => array(
          'media_default--media_browser_1' => 0,
          'media_default--media_browser_my_files' => 0,
          'media_internet' => 'media_internet',
          'upload' => 'upload',
          'youtube' => 0,
        ),
        'manualcrop_crop_info' => 1,
        'manualcrop_default_crop_area' => 1,
        'manualcrop_enable' => 0,
        'manualcrop_inline_crop' => 0,
        'manualcrop_instant_crop' => FALSE,
        'manualcrop_instant_preview' => 1,
        'manualcrop_keyboard' => 1,
        'manualcrop_maximize_default_crop_area' => 0,
        'manualcrop_require_cropping' => array(),
        'manualcrop_styles_list' => array(),
        'manualcrop_styles_mode' => 'include',
        'manualcrop_thumblist' => 0,
      ),
      'type' => 'media_generic',
      'weight' => 2,
    ),
  );

  // Exported field_instance: 'node-playbox_robot-field_playbox_powers'
  $field_instances['node-playbox_robot-field_playbox_powers'] = array(
    'bundle' => 'playbox_robot',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'This is an example of a power for a playbox character and the strength of that power. For example "Extreme Legislation: 76%". Each character will have 4 powers and you need input them like this "POWER/STRENGTH". Real world example: "Mega Buster/87". ',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 3,
      ),
      'featured' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_playbox_powers',
    'label' => 'Powers',
    'required' => 1,
    'settings' => array(
      'linkit' => array(
        'button_text' => 'Search',
        'enable' => 0,
        'profile' => '',
      ),
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 5,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('"Blue Bomber", "Phil Collins", "Zero", etc');
  t('A brief bio about your would-be robot overlord detailing things like how many humans he\'s vaporized or where he summered as a childbot.');
  t('Bio');
  t('Nickname');
  t('Portrait');
  t('Powers');
  t('This is a nice portrait of the challenging robot overlord.');
  t('This is an example of a power for a playbox character and the strength of that power. For example "Extreme Legislation: 76%". Each character will have 4 powers and you need input them like this "POWER/STRENGTH". Real world example: "Mega Buster/87". ');

  return $field_instances;
}
